---
- name: Create a data container for nginx
  docker_container:
    name: production_nginx
    image: nginx:latest
    volumes:
      - /vagrant/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    network_mode: host
    ports:
      - "8080:80"